-- MySQL Script generated by MySQL Workbench
-- Wednesday 18 July 2018 11:17:43 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eCheckout
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eCheckout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eCheckout` DEFAULT CHARACTER SET utf8 ;
USE `eCheckout` ;

-- -----------------------------------------------------
-- Table `eCheckout`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCheckout`.`customer` (
  `custId` VARCHAR(45) NOT NULL,
  `custName` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `eMail` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`custId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCheckout`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCheckout`.`product` (
  `productId` VARCHAR(45) NOT NULL,
  `productName` VARCHAR(45) NULL,
  `material` VARCHAR(45) NULL,
  `collection` VARCHAR(45) NULL,
  `length` DOUBLE NULL,
  `width` DOUBLE NULL,
  `colour` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`productId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCheckout`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCheckout`.`orders` (
  `orderNo` VARCHAR(45) NOT NULL,
  `customerId` VARCHAR(45) NULL,
  `productId` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `date` DATE NULL,
  `orderStatus` INT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`orderNo`),
  INDEX `customer_idx` (`customerId` ASC),
  INDEX `product_idx` (`productId` ASC),
  CONSTRAINT `customer`
    FOREIGN KEY (`customerId`)
    REFERENCES `eCheckout`.`customer` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product`
    FOREIGN KEY (`productId`)
    REFERENCES `eCheckout`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCheckout`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCheckout`.`cart` (
  `customerId` VARCHAR(45) NOT NULL,
  `productId` VARCHAR(45) NULL,
  `quantity` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`customerId`),
  INDEX `product_idx` (`productId` ASC),
  CONSTRAINT `customer`
    FOREIGN KEY (`customerId`)
    REFERENCES `eCheckout`.`customer` (`custId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product`
    FOREIGN KEY (`productId`)
    REFERENCES `eCheckout`.`product` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCheckout`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCheckout`.`admin` (
  `uname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`uname`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
